version: '3.8'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs
    ports:
      - 3000:3000
    volumes:
      - node_modules:/app/node_modules
      - .:/app
    env_file:
      - ./.env
    tty: true
    command: sleep infinity
    networks:
      - network

volumes:
  node_modules:
networks:
  network:
    driver: bridge
